// fetch_posters.py で自動生成
window.POSTERS={
 "Eyes of Wakanda": "/sCiX8QV8sY7WkOJkWCUrQj3xZ2h.jpg",
 "Captain America: The First Avenger": "/2YEbVbf4pSRv0o5T47V2typraZu.jpg",
 "Agent Carter": "/dNHb1Uietbae822lj1NLaqdeEtz.jpg",
 "Captain Marvel": "/bKFQqlpD1M7MnMeaIyUIYiAIdd9.jpg",
 "Iron Man": "/gZnH9qyt45WblCc9tEKlEXVjSKA.jpg",
 "Iron Man 2": "/mj12FOks34aSc7CXL8BpEFHXgrI.jpg",
 "The Incredible Hulk": "/p83fuvPHucZ1JO2EZ0bFjTlXf1f.jpg",
 "Thor": "/2xUDJQs4kGKeLszy9E9nD19DCLA.jpg",
 "The Avengers": "/l1SWn7SdwvAowNfC4ojV2B9LDgs.jpg",
 "Iron Man 3": "/cipMgzDMOSXygrXyCXVahNGQ1SK.jpg",
 "Thor: The Dark World": "/egWwgHwt8L3sukKBPT9UuOC1JPQ.jpg",
 "Agents of S.H.I.E.L.D.": "/46JrTCZTYlpLXPcQXVJJ5QiAggK.jpg",
 "Captain America: The Winter Soldier": "/npB83Gapjes4zsDMgeaMOp8xOgy.jpg",
 "Guardians of the Galaxy": "/HZ9wW4KbX73rR5PQpgsuOkCU99.jpg",
 "Guardians of the Galaxy Vol. 2": "/nXguM4n72qP4o3qFVTEWZ33pjpB.jpg",
 "I Am Groot": "/viyXnV8EPJTWmjK4dxdlZvMe20k.jpg",
 "Daredevil / Jessica Jones": "/kR2TJtfKxqNzPoM1HfLWjT90bHr.jpg",
 "Avengers: Age of Ultron": "/jSaRZoFY8gAioBO9nMnSGA3mjl6.jpg",
 "Ant-Man": "/7aqgrZYaRVCVsn11B6dXmxiXprn.jpg",
 "Captain America: Civil War": "/qCZnPrC5NGjnO7uTqCD5JkCBALQ.jpg",
 "Black Widow": "/5qJiKpvTWM0uj2S5tyjtWnMl1A5.jpg",
 "Black Panther": "/teEs4qQUKzxfYB7hDCZnIBzRYmd.jpg",
 "Spider-Man: Homecoming": "/x4uMWPwYUljcc6LWJSZNq19HryO.jpg",
 "Doctor Strange": "/u3IVExJVyFEiBW4xtIjQhWFuO38.jpg",
 "The Defenders Saga": "/gTohfbH01BDpRjYGWfgdSlnwVEa.jpg",
 "Thor: Ragnarok": "/22v9TpnY5doZg6muPKZTaHVmKmi.jpg",
 "Ant-Man and the Wasp": "/v357KzeDp6eKHDWxUOHODbbf2s5.jpg",
 "Avengers: Infinity War": "/4szrEPRLfw1iqk30tWywoL1uEqG.jpg",
 "Avengers: Endgame": "/uNWEDJzeH8VLHrs2iHkosYp2Y6W.jpg",
 "What If...?": "/4cCIHQo91crwy4C3ao3AIztoUlb.jpg",
 "Marvel Zombies": "/veBuhIjexLyidI1Owagj5L7oPmK.jpg",
 "Your Friendly Neighborhood Spider-Man": "/mloOt1HXlJpKVlv6hLxgR536htD.jpg",
 "WandaVision": "/lHe9I52U22xxWEa1b9Yb4CJBzwp.jpg",
 "The Falcon and the Winter Soldier": "/cBW6JMGhuAaQw4n3Ecv6PbA7DfP.jpg",
 "Spider-Man: Far From Home": "/tUzyW3leKzGeIcsMWld6cYhcO4b.jpg",
 "Eternals": "/15CiNXLhKI1Mn2paxit9Jei60S6.jpg",
 "Shang-Chi and the Legend of the Ten Rings": "/gKZpP4chV7t2ECQZRP0oLBHfPek.jpg",
 "Hawkeye": "/n6DA3z6uEzUGHpb2AyZdba2u1nU.jpg",
 "Echo": "/4166XH1ch9AWaO1G5vYrCXsD0MA.jpg",
 "Moon Knight": "/nm4xQDhSIFTee40fsRBvV9i1jwK.jpg",
 "Black Panther: Wakanda Forever": "/cB1kPUw8brtZRbXSKp1gdkWhd9q.jpg",
 "She-Hulk: Attorney at Law": "/3oQZwI9amhGVYQ7Syvh9FunWk1.jpg",
 "Ms. Marvel": "/34drYCa6yd4RWoO1aJH4CewjL0N.jpg",
 "Thor: Love and Thunder": "/pxhxlAkUxfLAb3dPBXcEEsSlncT.jpg",
 "Spider-Man: No Way Home": "/j2vwjzuofol93OcSn8xAHJiTEoz.jpg",
 "Doctor Strange in the Multiverse of Madness": "/uIBieATCKY8fnnCnDYoIffUMqP5.jpg",
 "Werewolf by Night": "/3SUskaGEvkdDw54oHf73ZKzl7Vk.jpg",
 "The Guardians of the Galaxy Holiday Special": "/7EMWk2JM7NutTcWzyyERLPnOHLB.jpg",
 "Guardians of the Galaxy Vol. 3": "/waTQqjV1dvGlbCAhN2VAIierdev.jpg",
 "Secret Invasion": "/fIm1Exwe7Q57z5jFM33l1w90A3f.jpg",
 "The Marvels": "/b6ipQGmVXqeyWLTbMxKCOWCuv1m.jpg",
 "Ant-Man and the Wasp: Quantumania": "/sF8z34NGwy1qGr3kWYIGgWO8hYl.jpg",
 "Loki": "/9XUsRYZv6RI1OoN1YT2rXZbpnM5.jpg",
 "Deadpool & Wolverine": "/3kQ7wDhrAd02fEwSBGQ1ZtCJDze.jpg",
 "Agatha All Along": "/gL6Vz7j87Xmp3EyCDJ9SsKOzzB7.jpg",
 "Ironheart": "/iVtO56WMWaZ4AMdmXWxty09zoui.jpg",
 "Daredevil: Born Again": "/eVs9txqAYDNCQlevGq1yA7hryYa.jpg",
 "Captain America: Brave New World": "/bvSaHm4mqNP20B0C00XRh0PeNHd.jpg",
 "Thunderbolts*": "/q9X2CbexqGwkpkVI8ORWkQ5vltj.jpg",
 "Wonder Man": "/jFgl6nRPZp4xD4uLj3MluYK0RUM.jpg",
 "Spider-Man: Brand New Day": "/hvbs76wGMZYqJSvaRps5jDzHUhN.jpg",
 "The Fantastic Four: First Steps": "/7AuLDxII9LcORX4dFa0QeXTqjyC.jpg",
 "VisionQuest": "/xK27l5uwaVyZSlENWnmLlWwDQNS.jpg",
 "Avengers: Doomsday": "/axD1jIfE2Is83vDKyTb1CnZ2EBt.jpg"
};
